server:
  port: 8000

spring:
  application:
    name: spring-cloud-eureka

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    hostname: localhost